version: "3.4"

services:
  sidecar:
    container_name: sidecar
    # image: gonitro/sidecar:b418716 # v2.1.5 - Works with Envoy v1.15.5
    image: mihaitodor/sidecar:latest # Contains https://github.com/NinesStack/sidecar/pull/66
    cap_add:
      - NET_ADMIN
    network_mode: host
    ports:
      - 7777 # Admin UI
      - 7946 # Memberlist port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      SidecarDiscover: "false"
    environment:
      # Use localhost as the default if no seed is injected at runtime via
      # ${SIDECAR_SEEDS}
      SIDECAR_SEEDS: ${SIDECAR_SEEDS:-127.0.0.1}
      SIDECAR_CLUSTER_NAME: dev
      # Exclude both the Sidecar internal loopback interface and the Docker
      # internal IPs
      SIDECAR_EXCLUDE_IPS: "192.168.168.168"
      # We inject the advertise IP to prevent Sidecar from trying to determine
      # it automatically because the code in sidecar/addresses.go keeps getting
      # confused due to Docker adding various "br-xxx" interfaces automagically.
      # Details here: https://github.com/moby/moby/issues/37823#issuecomment-421186655
      SIDECAR_ADVERTISE_IP: ${ADVERTISE_IP:-}
      HAPROXY_DISABLE: "true"
      # Needs to be set because Sidecar's run script doesn't look at ENVOY_BIND_IP
      # TODO: Fix this...
      HAPROXY_BIND_IP: "192.168.168.168"
      ENVOY_GRPC_PORT: 7776
      ENVOY_BIND_IP: "192.168.168.168"
      ENVOY_LOGGING_LEVEL: debug

  envoy:
    container_name: envoy
    # image: envoyproxy/envoy:v1.15.5
    image: envoyproxy/envoy:v1.21.1
    # entrypoint: /usr/local/bin/envoy
    command: --service-cluster dev --service-node ${HOSTNAME:?HOSTNAME not set} --config-path /etc/envoy/${ENVOY_CONFIG:?ENVOY_CONFIG not set}
    network_mode: host
    ports:
      - 9901 # Admin UI
    volumes:
      - /etc/envoy:/etc/envoy
      - /etc/envoy/ssl:/etc/envoy/ssl
    labels:
      SidecarDiscover: "false"
    environment:
      MESOS_HOSTNAME: ${HOSTNAME:?HOSTNAME not set}
      CLUSTER_NAME: dev
      BIND_IP: "192.168.168.168"
  envoy-ui:
    container_name: envoy-ui
    image: gonitro/envoy-ui:42bae1c
    # Hack: Run this in host networking mode to avoid injecting the parent
    # container IP via some env var
    network_mode: host
    ports:
      - 7778 # UI
    labels:
      SidecarDiscover: "false"
    environment:
      ENVOY_UI_HOST: localhost
      ENVOY_UI_PORT: 9901
      ENVOY_UI_LISTEN_PORT: 7778
